services:
  nginxmtls:
    build: .
    container_name: nginxmtls
    ports:
#      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
      - ./nginx/certs:/etc/nginx/cert
    networks:
      - nginx
networks:
  nginx:
    driver: bridge
    name: nginx
